"""add sentiment and severity to map_alerts

Revision ID: 10a2967fbff3
Revises: f8069b7e1390
Create Date: 2026-05-11 16:59:53.457265

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10a2967fbff3'
down_revision: Union[str, Sequence[str], None] = 'f8069b7e1390'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('map_alerts', sa.Column('severity_label', sa.String(length=50), nullable=False))
    op.drop_column('map_alerts', 'severity_score')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('map_alerts', sa.Column('severity_score', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_column('map_alerts', 'severity_label')
    # ### end Alembic commands ###
