"""initial_migration

Revision ID: 34a435ba6f06
Revises: 
Create Date: 2026-05-06 16:26:13.030551

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34a435ba6f06'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('map_alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('raw_event_id', sa.Integer(), nullable=False),
    sa.Column('extracted_locations', sa.JSON(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('sentiment_score', sa.Float(), nullable=False),
    sa.Column('severity_score', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('map_alerts')
    # ### end Alembic commands ###
