"""add sentiment and severity columns

Revision ID: f8069b7e1390
Revises: 6402feb9cd1f
Create Date: 2026-05-11 16:41:01.107162

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8069b7e1390'
down_revision: Union[str, Sequence[str], None] = '6402feb9cd1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('map_alerts', sa.Column('sentiment_score', sa.Float(), nullable=False))
    op.add_column('map_alerts', sa.Column('severity_score', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('map_alerts', 'severity_score')
    op.drop_column('map_alerts', 'sentiment_score')
    # ### end Alembic commands ###
